let places={60:"Kuala Lumpur",
42:"Petaling Jaya",
  20: "Ampang",
  21: "Ara Damansara",
  22: "Bangsar",
  23: "Bangsar South",
  24: "Bukit Bintang",
  26: "Damansara",
  27: "Cheras",
  29: "Damansara Heights",
  30: "Damansara Perdana",
  31: "Damansara Utama",
  62: "Ipoh",
  33: "Kelana Jaya",
  34: "Kepong",
  35: "Klang",
  37: "Kota Damansara",
  39: "Mont Kiara",
  40: "Mutiara Damansara",
  41: "Old Klang Road",
  44: "Puchong",
  45: "Pudu",
  46: "Putrajaya",
  48: "Sepang",
  50: "Seri Kembangan",
  51: "Setapak",
  52: "Shah Alam",
  53: "Sri Hartamas",
  54: "Sri Petaling",
  55: "Subang",
  56: "Taman Desa",
  58: "Taman Tun",
}

export {places}